"""Add grade

Revision ID: 01da5005c07e
Revises: b662c9070fbd
Create Date: 2026-01-08 17:01:24.376710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01da5005c07e'
down_revision: Union[str, Sequence[str], None] = 'b662c9070fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('grade', sa.String(), nullable=True))
    op.create_index(op.f('ix_vacancies_grade'), 'vacancies', ['grade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_grade'), table_name='vacancies')
    op.drop_column('vacancies', 'grade')
    # ### end Alembic commands ###
