"""Add company_logo and salary_in_kzt columns

Revision ID: 14e540b709c1
Revises: 01da5005c07e
Create Date: 2026-01-09 18:21:58.664916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e540b709c1'
down_revision: Union[str, Sequence[str], None] = '01da5005c07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('company_logo', sa.String(), nullable=True))
    op.add_column('vacancies', sa.Column('salary_in_kzt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'salary_in_kzt')
    op.drop_column('vacancies', 'company_logo')
    # ### end Alembic commands ###
