"""Add is_ai_checked to Vacancy

Revision ID: 3b043e3c8ab3
Revises: 395aafe1b4af
Create Date: 2026-01-11 00:28:51.117787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b043e3c8ab3'
down_revision: Union[str, Sequence[str], None] = '395aafe1b4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('is_ai_checked', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_vacancies_is_ai_checked'), 'vacancies', ['is_ai_checked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_is_ai_checked'), table_name='vacancies')
    op.drop_column('vacancies', 'is_ai_checked')
    # ### end Alembic commands ###
