"""add_username_to_user

Revision ID: 9814638408d9
Revises: 77e6a7c48dc9
Create Date: 2026-02-09 00:29:39.274603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9814638408d9'
down_revision: Union[str, Sequence[str], None] = '77e6a7c48dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable first
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    
    # 2. Update existing users to have a username based on their email prefix
    op.execute("UPDATE users SET username = split_part(email, '@', 1)")
    
    # 3. Make column non-nullable
    op.alter_column('users', 'username', nullable=False)
    
    # 4. Create index
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
