"""Initial migration

Revision ID: 99328140a958
Revises: 
Create Date: 2026-01-08 13:43:43.184454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99328140a958'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_from', sa.Integer(), nullable=True),
    sa.Column('salary_to', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), server_default='KZT', nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'source', name='unique_external_vacancy'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_vacancies_external_id'), 'vacancies', ['external_id'], unique=False)
    op.create_index(op.f('ix_vacancies_location'), 'vacancies', ['location'], unique=False)
    op.create_index(op.f('ix_vacancies_published_at'), 'vacancies', ['published_at'], unique=False)
    op.create_index(op.f('ix_vacancies_title'), 'vacancies', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_title'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_published_at'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_location'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_external_id'), table_name='vacancies')
    op.drop_table('vacancies')
    # ### end Alembic commands ###
