"""add_company_name_field

Revision ID: a11082f78ce6
Revises: abe81420e354
Create Date: 2026-02-02 22:08:05.514595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11082f78ce6'
down_revision: Union[str, Sequence[str], None] = 'abe81420e354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('company_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_vacancies_company_name'), 'vacancies', ['company_name'], unique=False)

    # Backfill company_name from raw_data->'employer'->>'name'
    op.execute("""
        UPDATE vacancies
        SET company_name = raw_data->'employer'->>'name'
        WHERE company_name IS NULL
          AND raw_data->'employer'->>'name' IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_company_name'), table_name='vacancies')
    op.drop_column('vacancies', 'company_name')
    # ### end Alembic commands ###
