"""add_user_profile_fields

Revision ID: abe81420e354
Revises: 504ca7f1eba7
Create Date: 2026-01-12 12:27:47.059578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abe81420e354'
down_revision: Union[str, Sequence[str], None] = '504ca7f1eba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'grade')
    op.drop_column('users', 'location')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
