"""Add experience, employment, schedule

Revision ID: b662c9070fbd
Revises: 1c9210f594be
Create Date: 2026-01-08 16:27:04.706547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b662c9070fbd'
down_revision: Union[str, Sequence[str], None] = '1c9210f594be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('vacancies', sa.Column('employment', sa.String(), nullable=True))
    op.add_column('vacancies', sa.Column('schedule', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'schedule')
    op.drop_column('vacancies', 'employment')
    op.drop_column('vacancies', 'experience')
    # ### end Alembic commands ###
