"""Add index on salary_in_kzt

Revision ID: d8e2a5061b8d
Revises: 14e540b709c1
Create Date: 2026-01-09 18:33:13.551338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e2a5061b8d'
down_revision: Union[str, Sequence[str], None] = '14e540b709c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vacancies_salary_in_kzt'), 'vacancies', ['salary_in_kzt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_salary_in_kzt'), table_name='vacancies')
    # ### end Alembic commands ###
