"""add_search_vector

Revision ID: dac97c260c85
Revises: a11082f78ce6
Create Date: 2026-02-05 15:17:40.231277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dac97c260c85'
down_revision: Union[str, Sequence[str], None] = 'a11082f78ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', title || ' ' || coalesce(description, ''))", persisted=True), nullable=True))
    op.create_index('ix_vacancies_search_vector', 'vacancies', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacancies_search_vector', table_name='vacancies', postgresql_using='gin')
    op.drop_column('vacancies', 'search_vector')
    # ### end Alembic commands ###
